name: Run a Docker image

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Clone, Publish
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build and publish to GitHub Packages
        uses: docker://docker.pkg.github.com/emmanuel-guisse-ledger/test-github-workflow/test-github-workflow:latest
        args:
          - 'echo bonjour'
