name: Run a Docker image

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Clone, Publish
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Docker Login
        run: echo $GITHUB_TOKEN | docker --debug --config /tmp/.docker login https://docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_ACTOR: ${{ github.actor }}
      - name: Pull Docker image
        run: docker --debug --config /tmp/.docker pull docker.pkg.github.com/emmanuel-guisse-ledger/test-github-workflow/test-github-workflow:latest
      - name: List Docker image
        run: docker images
      - name: Run image
        run: |
          docker --debug --config /tmp/.docker run --rm -v "$(pwd):/mnt:rw" docker.pkg.github.com/emmanuel-guisse-ledger/test-github-workflow/test-github-workflow:latest echo "Hello world!"
