name: Run a Docker image

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Clone, Publish
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2
        run: echo $GITHUB_TOKEN | docker login 'docker.pkg.github.com' -u '$GITHUB_ACTOR' --password-stdin
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_ACTOR: ${{ github.actor }}
      - name: Pull Docker image
        run: docker pull "docker.pkg.github.com/emmanuel-guisse-ledger/test-github-workflow/test-github-workflow:latest"
      - name: Run image
        run: |
          docker run --rm -v "$(pwd):/mnt:rw" docker.pkg.github.com/emmanuel-guisse-ledger/test-github-workflow/test-github-workflow:latest echo "Hello world!"


